/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Negocios.Bingo;
import Negocios.Cartilla;
import static java.lang.String.valueOf;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brand
 */
public class JuegoPrincipal extends javax.swing.JFrame {
    private static final int NumeroDeColumnas = 5;

    /**
     * Creates new form JuegoPrincipal
     */
     Bingo B;
    Cartilla cartilla;
    Random R;
    public JuegoPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MostrarCartilla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cartillas = new javax.swing.JTable();
        NumeroDeCartillaOrdinal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RangoDeNumeros = new javax.swing.JTextField();
        CantidadDeNumerosEnCartilla = new javax.swing.JTextField();
        CrearBINGO = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CantidadDeCartillas = new javax.swing.JTextField();
        NumeroSorteado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnSortear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MostrarCartilla.setText("Mostrar Cartilla");
        MostrarCartilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarCartillaActionPerformed(evt);
            }
        });

        Cartillas.setBackground(new java.awt.Color(51, 51, 255));
        Cartillas.setFont(new java.awt.Font("Hack", 1, 20)); // NOI18N
        Cartillas.setForeground(new java.awt.Color(255, 255, 255));
        Cartillas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Cartillas.setGridColor(new java.awt.Color(255, 255, 255));
        Cartillas.setName("BINGO"); // NOI18N
        Cartillas.setRowHeight(30);
        Cartillas.setSelectionBackground(new java.awt.Color(0, 0, 0));
        Cartillas.setShowGrid(true);
        jScrollPane1.setViewportView(Cartillas);

        jLabel1.setText("NumeroMaximo");

        jLabel2.setText("CantidadDeNumeros");

        jLabel3.setText("NumeroDeCartilla");

        CrearBINGO.setText("CrearBingo");
        CrearBINGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBINGOActionPerformed(evt);
            }
        });

        jLabel5.setText("CantidadDeCartillas");

        NumeroSorteado.setBackground(new java.awt.Color(255, 0, 0));
        NumeroSorteado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        NumeroSorteado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));

        jLabel6.setText("Bolilla Nº");

        BtnSortear.setText("SortearNumero");
        BtnSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSortearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RangoDeNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(CantidadDeNumerosEnCartilla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(NumeroDeCartillaOrdinal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CantidadDeCartillas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MostrarCartilla)
                    .addComponent(CrearBINGO))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(75, 75, 75)
                .addComponent(BtnSortear)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CantidadDeNumerosEnCartilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(CantidadDeCartillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(RangoDeNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MostrarCartilla)
                            .addComponent(NumeroDeCartillaOrdinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(CrearBINGO)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnSortear)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarCartillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarCartillaActionPerformed
    
        int numeroCartilla = Integer.parseInt(NumeroDeCartillaOrdinal.getText());
        
    String cartillaString = B.imprimirCartilla(numeroCartilla);
    System.out.println(cartillaString);

    DefaultTableModel tableModel = (DefaultTableModel) Cartillas.getModel();
    tableModel.setRowCount(0); // Limpiar las filas existentes

    try {
        int InicialIndex = cartillaString.indexOf("[N=") + 3;
        int FinalIndex = cartillaString.indexOf("]");
        if (InicialIndex >= 3 && FinalIndex > InicialIndex) {
            String NumeroString = cartillaString.substring(InicialIndex, FinalIndex);
            String[] NumerosArray = NumeroString.split(",");

            for (int i = 0; i < NumerosArray.length; i += NumeroDeColumnas) {
                String[] row = new String[NumeroDeColumnas];
                for (int j = 0; j < NumeroDeColumnas; j++) {
                    if (i + j < NumerosArray.length) {
                        row[j] = NumerosArray[i + j];
                    } else {
                        row[j] = ""; // Dejar vacío si no hay más números
                    }
                }
                tableModel.addRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(this, "La cadena de cartilla no tiene el formato esperado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Ocurrió un error al procesar la cadena de cartilla: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_MostrarCartillaActionPerformed

    private void CrearBINGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBINGOActionPerformed
        int cantCartillas=Integer.parseInt(CantidadDeCartillas.getText());
         int RangoMaximo= Integer.parseInt(RangoDeNumeros.getText());
        int CantidadDeNumeros=Integer.parseInt(CantidadDeNumerosEnCartilla.getText());
        B=new Bingo(cantCartillas,RangoMaximo);
        B.CrearBingo(RangoMaximo,CantidadDeNumeros);
       
        
    }//GEN-LAST:event_CrearBINGOActionPerformed

    private void BtnSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSortearActionPerformed
        int RangoMaximo= Integer.parseInt(RangoDeNumeros.getText());
       // B.sortearNumero(RangoMaximo);
        //B.sortearUnNumero();
        //int NumeroSorteado = B.sortearNumero(RangoMaximo);
        String NumeroSorteado2= String.valueOf(B.sortearNumero(RangoMaximo));
        
        NumeroSorteado.setText(NumeroSorteado2);
        System.out.println(NumeroSorteado2);
    }//GEN-LAST:event_BtnSortearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSortear;
    private javax.swing.JTextField CantidadDeCartillas;
    private javax.swing.JTextField CantidadDeNumerosEnCartilla;
    private javax.swing.JTable Cartillas;
    private javax.swing.JButton CrearBINGO;
    private javax.swing.JButton MostrarCartilla;
    private javax.swing.JTextField NumeroDeCartillaOrdinal;
    private javax.swing.JTextField NumeroSorteado;
    private javax.swing.JTextField RangoDeNumeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
